core:
  cron: "0 8-20 * * *"
  location: "Europe/Ljubljana"
  logging:
    level: "info"
    type: "console"
    time_format: "rfc3339"
notifications:
  discord:
  - name: "discord-monitoring"
    webhook: "https://discord.com/api/webhooks/*******************/********************************************************************"
repositories:
- name: "aJuvan/release-notify"
  prerelease: false
  tag_regex: "v.*"
  notification_channels:
  - "discord-monitoring"
